pipeline {
    agent any
    parameters {
        choice(name: 'BROWSER', choices: ['CHROME', 'EDGE'], description: 'Select Browser')
        string(name: 'TAGS', defaultValue: '@Test1', description: 'Enter Cucumber tags')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat "mvn test -DsuiteXmlFile=testng.xml -Dbrowser=${params.BROWSER} -Dcucumber.filter.tags=\"${params.TAGS}\""
            }
        }
    }
    post {
        always {
            // echo "Reporting........"
            // archiveArtifacts artifacts: 'target/*.json', fingerprint: true

            echo "Reports will be generated automatically in Maven verify phase"

//            bat 'dir /s target\\*.json'
//
//            junit '**/target/surefire-reports/*.xml'
//
//            allure includeProperties: false,
//                    jdk: '',
//                    results: [[path: 'target/allure-results']]
//
//            cucumber buildStatus: 'UNSTABLE',
//                    fileIncludePattern: '**/cucumber-test*.json',
//                    jsonReportDirectory: 'target'
//            zip zipFile: 'Automation_Report.zip', dir: 'target'

            archiveArtifacts artifacts: 'Automation_Report.zip', allowEmptyArchive: true

            // archiveArtifacts artifacts: 'target/*.html, target/*.json', allowEmptyArchive: true
        }
    }
}
