pipeline {
    agent any

    stages {
          stage('Checkout') {
            steps {
                echo "Checking........"
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo "Building........"
                bat 'mvn clean'
            }
        }
        stage('Test') {
            steps {
                echo "Testing........"
                bat 'mvn test'
            }
        }
        stage('Report') {
            steps {
                echo "Reporting........"
                archiveArtifacts artifacts: 'target/*.json', fingerprint: true
            }
        }
    }
}
